### ISSUE TITLE
Add global routes to Gate

### ISSUE THREAD

**Issue by frgt** [gemelen/sgbplus#5]
As we discussed, `Gate` should provide 3 default routes:

- `post("login") // login: String, password: String`
- `post("logout") // parameterless, CSRF-protected (requires token in header)`
- `get("token") // parameterless, returns CSRF token`

**Comment by gemelen** [comment]
My point that /login and /token shouldn't be protected, all other endpoints need to require token in header

**Comment by frgt** [comment]
Updated description

**Comment by frgt** [comment]
Closing since PR #6 was merged
